### PR TITLE
Classpath libs

### PR DESCRIPTION
**Pull request by puce77**
- jfxBinDir property added (default: "")
- jfxLibDir property added (default: "lib")
- skipCopyDependenciesToLibDir property added
- Manifest Class-Path calculated from lib directory to include JAR-files copied to the lib dir by other Maven Plugins

### CODE REVIEW

**Comment by puce77** [comment]
@FibreFoX Could you double-check if the run, native and web Mojos still behave as expected (in a backwards compatible manner). I'm not very familiar with these Mojos.

**Comment by FibreFoX** [comment]
Thanks for this PR, will have to check those MOJOs and might change a bit, mostly formatting. But will take some days, I'm pretty busy this weekend.

**Comment by puce77** [comment]
@FibreFoX Why has this PR been closed? I would have preferred if we could have worked with the branch rather than duplicate things but in a different way on another PR. Now it will be hard to find the missing pieces (one reason I would have preferred small PRs).

I don't see a binDir property in the new PR. In order to integrate this plugin with the Drombler FX Maven Plugin, I have to find a way to support the following application layout:

app/bin
app/bin/foo.jar (created by build-jar)
app/bin/foo (copied from additionalAppResources)
app/bin/lib
app/bin/lib/some.jar (copied by Drombler FX Plugin)
app/conf
app/conf/someproperties.properties (copied from additionalAppResources)
app/bundle
app/bundle/osgiBundle.jar (copied by Drombler FX Maven Plugin)

Also all the various integration tests I wrote for this plugin are now missing.

Please advice how you would like to proceed from here.

**Comment by FibreFoX** [comment]
I know that I hurt your feelings, and I'm very sorry, you rushed so fast that I couldn't reach you that fast.

Why should I need a `binDir`? I don't really get why it is needed for this plugin. For the layout you might want to change `jfxAppOutputDir` from `${project.build.directory}/jfx/app` to `${project.build.directory}/jfx/app/bin`, but the `conf`-folder has to come from your plugin, as it is a custom layout.
Please keep in mind, that the javafx-maven-plugin is just a wrapper of the original/official `javapackager`, there are a lot of conventions there which I don't like myself, but have to bare with them.

As the IT-projects were special dromber-fx use-cases, which this plugin does not cover (yet), and being incompatible with the way I prefered to implement them, this PR got closed. Some changes were too much, because the previous behaviour (even not the best ones) were changed, which I don't like that much.

🍰 please don't take it personally :(

**Comment by FibreFoX** [comment]
Just some additional thoughts: is the `binDir` really needed for the jfx-jar? To have it bundled with the custom layout you might want to change it to `${project.build.directory}/jfx/app/bin` while calling `build-jar`, and than change it back when calling `build-native`. Don't know if it works or not.

**Comment by puce77** [comment]
I understand that the JavaFX Maven Plugin is basically a wrapper for the javapacker tool.

But the plugin does several things:

- it creates a JAR file
- it copies dependencies/ calculates the Manifest Class-Path from a lib directory
- it copies additional resources
- it creates native packages
- it runs the application
- ...

It's an assumption of the plugin that everything is located in the same directory, not an assumption of the javapacker tool, AFAIK.

All I'm asking is for a possibilty to configure the plugin so that the JAR file and the lib directory are located in a sub-directory of the app directory (which is used by the additional resource copy and the native packagers).

Maybe "binDir" was a bad name and too Drombler FX specific.
Maybe something like "jarParentFolderName"?

E.g. with the following configuration:
jfxAppOutputDir = ${project.build.directory}/jfx/app (default)
jarParentFolderName = a1/a2 (default "" or ".")
libFolderName = b1/b2 (default "lib")

The jar should be created at: ${project.build.directory}/jfx/app/a1/a2
The dependencies should be copied to: ${project.build.directory}/jfx/app/a1/a2/b1/b2
The Manifest Class-Path entries should start with: b1/b2/
The additional resources should be copied to: ${project.build.directory}/jfx/app
The native packager should work on: ${project.build.directory}/jfx/app

To support only a single level for jarParentFolderName and libFolderName would also be enough at least for my use case and might be easier to implement.

I already tried your proposal to set jfxAppOutputDir to ${project.build.directory}/jfx/app/bin before my initial binDir proposal but I soon realized that things will get quickly messy when the meaning of jfxAppOutputDir changed during one build. It would be messy for the Drombler FX Maven Plugin and very difficult for developers to tweak the two plugins for their needs.

So I really need some kind of configuration possibility here.

**Comment by FibreFoX** [comment]
@puce77 please take a look at https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/274
I just saw that you might not have recieved the notifications on that thread

**Pull request closed without merging**
