### PR TITLE
Additional app resources

### PR DESCRIPTION
**Pull request by puce77**
- Added property names jfx.additionalAppResources and jfx.copyAdditionalAppResourcesToJar
- Fail on failed files during copy

Please merge after PR #259 as this contains the commits of that PR as well.

### CODE REVIEW

**Comment by FibreFoX** [comment]
This commit seems odd: https://github.com/Drombler/javafx-maven-plugin/commit/3c1a8a7c2a26538f1a01af6dcc45f34a8bb04be4

Why changing the current behaviour?

**Comment by puce77** [comment]
@FibreFoX I think it is extremly dangerous to ignore failed file copies just with a warning. In my experience developers often to have the time to fix all warnings/ keep an eye on them. So this will end up in incomplete bundles which is hard to detect. Depending on how heavily the product is tested and in which scenarios the resource is used this might even slip to production.

Do you know any use case where you actually do want to ignore a failed file copy rather than to fix the issue?

**Comment by FibreFoX** [comment]
The thing is, it's logged as WARNING. If developers keep ignoring warnings inside the build-log, they are just ignorant to important feedback. Failing to copy some files should not avoid the whole creation-process. In the scenario where the build is done as different user, there might be file-permission problems, which are logged as WARNINGS (because maybe it is wanted as part of some paranoid protection) and visible to the user.

**Comment by JustGregory** [comment]
I second what Danny said. You would not believe how often self-styled "genius" programmers actually ignore warnings (either by configuring their IDE to not show them, or by pretending they don't see them). The pursuit of a successful build cycle is not an ending in and of itself, but must always take into account the potential obstacles to the build process.

**Comment by puce77** [comment]
It doesn't matter if we think developers should look at the warnings or not, fact is that developers often don't. Maven Plugins often create warnings which can be safely ignored, but this warning mustn't be ignored! In big companies there are many build running per day on CI servers, and e.g. Jenkins doesn't indicate if there was Maven warning. The build is just green. And for this particular warning checking build X wouldn't guarantee you that build X+1 doesn't have an IO issue.
You could say that you should at least check the build when you do a release, but then again the release is already finished once you can check the log instead of Maven stopping the release.
And if developers don't check the logs (in my experience most of the time) they can end-up with an incomplete release which might put this Maven plugin if not JavaFX in a bad light.

If this still doesn't convince you and you think there is a use case for this warning then at least need a flag where I can control this.

**Comment by FibreFoX** [comment]
`A fool with a tool, is still a fool`
It IS THE RESPONSABILITY of the developer, to make sure it works on the CI-server, not mine. As I wrote on a different comment, I will reconsider and check for a new failing-flag.

**Pull request closed without merging**
