### PR TITLE
template support, appName parameter, default values for title and description

### PR DESCRIPTION
**Pull request by francesco-kriegel**
Hi @FibreFoX,
this pull request for the WebMojo offers the following features:
1. template support
2. a parameter for appName
3. new default values for title and description parameters (uses values from pom.xml)

This is a follow-up of pull request [94](https://github.com/javafx-maven-plugin/javafx-maven-plugin/pull/94).

### CODE REVIEW

**Comment by francesco-kriegel** [comment]
Furthermore, parameters for appName, title, and description have been introduced to the NativeMojo.

PS: Unfortunately, it is not possible to open different pull requests from the same fork.

**Comment by francesco-kriegel** [comment]
Last but not least, the last commit offers the possibility to specify an existing jar file, e.g., a jar-with-dependencies from maven-assembly-plugin; and furthermore a switch to enable/disable the creation of the libDir (which is not needed for a jar-with-dependencies).

**Comment by francesco-kriegel** [comment]
Another change: If the nativeReleaseVersion value is not set then it is automatically created from ${project.version} by removing all non-numeric characters except dots.

**Comment by FibreFoX** [comment]
Hi, it is possible to work on different branches, so every feature has its own git-branch, which are all based on current master.

As mentioned within PR #94 we won't accept PRs with multiple fixes, especially with different aspects changing.

About some changes: for what I know, having a fat-jar isn't always the best solution, that was one reason for a complete rewrite of this plugin. Would be nice if you could write some benefits with that strategy.
The attributes for JNLP "title" and "description" are already set within [WebMojo](https://github.com/francesco-kriegel/javafx-maven-plugin/blob/master/src/main/java/com/zenjava/javafx/maven/plugin/WebMojo.java#L168).

**Comment by francesco-kriegel** [comment]
Hi, when packing my software project there were some problems during signing third-party-jars. If the maven-assembly-plugin is used then only this one jar has to be signed and no problems occur. Hence, the usage of the "fat-jar" is advantageous here. For me it does not matter whether I have one or several jars containing the same code.

I won't find the time to create different branches for this pull request in this week. Maybe you can still merge the changes.

**Comment by maxd** [comment]
No, we can't merge this PR because we don't have a time to code-review mixed features and support them too :) I hope you can find a time later and provide this features in separate branches. Moreover will be better to have [integration tests](https://github.com/javafx-maven-plugin/javafx-maven-plugin/tree/master/src/it) for this features.

I close it.

**Pull request closed without merging**
