### PR TITLE
Add Maven Central link

### PR DESCRIPTION
**Pull request by hinerm**

### CODE REVIEW

**Comment by maxd** [comment]
Is it possible to remove version from link? Very easy to forget change it.

**Comment by hinerm** [comment]
@maxd certainly - I updated to to [all versions, latest first](https://search.maven.org/#search|gav|1|g%3A%22com.zenjava%22%20AND%20a%3A%22javafx-maven-plugin%22). As far as I could tell, `search.maven.org` doesn't allow `version=LATEST` which I think would've been ideal.

**Comment by FibreFoX** [comment]
There is another URL for this, and its pointing to the latest version:
https://maven-badges.herokuapp.com/maven-central/com.zenjava/javafx-maven-plugin

I hope it's okay for everyone to drop this PR and use the herokuapp-link?

**Comment by maxd** [comment]
:+1:

**Comment by hinerm** [comment]
@FibreFoX excellent, glad there's a better link to use!

**Pull request closed without merging**
