### PR TITLE
added integration tests via maven-invoker-plugin

### PR DESCRIPTION
**Pull request by FibreFoX**
found and fixed problem with manifestAttributes (had to remove default-value)

Note: these testing-projects could be used as example-projects too :smile: and we can add projects for bug-scenarios

### CODE REVIEW

**Comment by FibreFoX** [comment]
Dont merge this yet ... travis is failing, I will report if fixed

**Comment by FibreFoX** [comment]
Okay ;) travis is running, can be merged now

**Comment by maxd** [comment]
I see that most of commit files contains TABs not converted to SPACEs. How about use SPACEs everywhere?

**Comment by FibreFoX** [comment]
Woops, I will check and fix this. Thanks @maxd , when having this fixed, I'm going to merge this.

**Pull request merged**
