### PR TITLE
Update GenerateKeyStoreMojo.java

### PR DESCRIPTION
**Pull request by michoo**
I'm not sure for "\""....

### CODE REVIEW

**Comment by maxd** [comment]
@michoo Could you please explain this PR? Which problem should it fix?

**Comment by FibreFoX** [comment]
@michoo i see that fix about certState being "s" and not "st", but could you rework the appending of that comma?
more like this
```
if(alreadyAppendedSomething){
domainName.append(", ");
}
(...normal stuff...)
```
we might end up with ```, ``` dangeling at the end of the string

please remove the "\""-part and check generation (i see that we need tests for this)

**Comment by FibreFoX** [comment]
I'm closing this, because I'm going to refactor this. Doing some research for that *"s="* or *"ST="*-question, i stumbled upon some mistakes inside oracle-documentation.
Searching for some specs about **"Distinguished Names"** got me this results:

source: http://docs.oracle.com/javase/8/docs/technotes/tools/unix/keytool.html
fieldname: "S="
    
http://www.zytrax.com/tech/survival/ssl.html
fieldname: **"ST="**

http://tools.ietf.org/rfc/rfc5280.txt
referrs to: https://www.ietf.org/rfc/rfc4514.txt
fieldname: **"ST="**

https://msdn.microsoft.com/en-us/library/aa366101%28v=vs.85%29.aspx
fieldname: **"ST="**

http://www.windowsnetworking.com/articles-tutorials/netgeneral/Networking-Basics-Part10.html 
referrs to: http://www.faqs.org/rfcs/rfc2253.html
fieldname: **"ST="**
    
http://stackoverflow.com/a/3284135/1961102
referrs to: http://i.imgur.com/VgLUO.png
fieldname: **"ST="**

Generating keystore seems broken and has to be reworked!

**Comment by FibreFoX** [comment]
From the documentation of keytool: "The keytool command does not enforce all of these rules so it can generate certificates that do not conform to the standard. Certificates that do not conform to the standard might be rejected by JRE or other applications. Users should ensure that they provide the correct options for -dname, -ext, and so on."

**Pull request closed without merging**
